### ISSUE TITLE
paxmod SUCKS

### ISSUE THREAD

**Issue by smihaila** [numirias/paxmod#102]
I am sorry, but your Firefox extension (which which required me to explicitly part away away with my existing Firefox NON-developer installation and installing instead the Firefox Developer edition) SUCKS ASS.

It is miles away from "Quantum Nox Firefox Dark Full Theme" ( https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme ), in the sense that it does makes the Windows right-top minimize/restore/maximize standard icons/buttons size GROW with the number of multiple rows that are currently showing through the firefox extension. It is UGLY, and bad functionality.

Can you please make your software component behave 100% lile the "Quantum Nox Firefox Dark Full Theme"? Can you make those standard buttons NOT grow with the number of tab multi-rows currently showing?

Until then, sorry, but your work is simply a disappointment, and has wasted my time.
You SUCK!

**Comment by mcdonnnj** [comment]
I mean put bluntly if you don't like a project then do one of the following:

1. Leave constructive feedback.
2. Contribute to improve the project.
3. Don't use it and move on.

You've managed to do none of these things. In this particular case if you are such a fan of Quantum Nox you can fork the archived repository and update it to work with newer versions of Firefox instead of leaving rude issues in other users' projects.

**Comment by smihaila** [comment]
Sorry for being too abrasive about this, but the whole multi-row tab support situation (rather the lack thereof) is simply frustrating.

We are at the end of 2022, and Mozilla is blatantly adverse to multi-row tabs. Soon following Google's arrogance (whose so-called "system architects" and "UX designers" are "telling us" - from a high horse position, what our needs _should _be__ instead of listening to what the Users' **wants** really are).

I've found out in the meantime that TabMixPlus can work with the latest Firefox 108.0 release, via the "userChromeJS" layer, which brings back "legacy" support, thus allowing the TabMixPlus' .xpi modules to be loaded:
https://github.com/onemen/TabMixPlus
https://github.com/xiaoxiaoflood/firefox-scripts#instructions
I've just tried it, and it seems to be working very well.
Uninstalling the Firefox Developer edition and the paxmod, since I've found a great replacement solution for Quantum Nox.

Anyways, best of luck with your project!

**Comment by Ryosuke-Asano** [comment]
Paxmod works with a different mechanism than TabMixPlus, which works with Webextension's mechanism, so the comparison is incorrect.  Webextension is more modern.

Also, issues are not the place to complain about development.

**Comment by ptsneves** [comment]
@smihaila you can always get your sleeves up and do it better. Please don't waste everybody's time with your whining. 

@numirias I would like to compensate you for the trouble of @smihaila and would like to send you a small donation for your work. If you add the github sponsor I will drop some cash.

**Comment by smihaila** [comment]
@ptsneves What about my wasted time with this software solution? Pure waste of time having to install a Firefox developer edition, having to get used to using it for about 2 weeks, and so and so forth, realizing it's not useful, and then having to uninstall such firefox and putting back the normal firefox edition again.

Anyways, I wish you best of luck in endeavors. On my side, I have moved away from this POS. TMP rocks - that's a successful solution!
