### ISSUE TITLE
Stopped working in Nightly 2024-08-22

### ISSUE THREAD

**Issue by sinyb** [numirias/paxmod#113]
**Describe the bug**
Since Nightly 131.0a1 (2024-08-22) there are no more multiple rows, only one row is displayed, but I can go to other tabs with Ctrl-PgUp/PgDn

**Environment**
OS Linux (opensuse, current) and Windows 10, Firefox Nightly 131.0a1 (2024-08-22+), Paxmod version 3.16

**Comment by GIS1980** [comment]
@sinvb - happened for me also. 
"You don't know what you got 'til it's gone".

**Comment by gammy** [comment]
Same here but a different date: 
Firefox `131.0a1 (2024-08-24) (64-bit)`, 
Paxmod `3.16 (April 28, 2024)`
`Debian trixie (testing)`,  but I suspect that's irrelevant.

Paxmod is still active and running; color attributes and fixed-width is still there, but not multi-row tabs. It seems it also breaks the stock firefox behavior (not too surprising) in that I can only see the top row of tabs (but not the rest). Pinned tabs are not visible.

**Comment by Wolferine69** [comment]
same here..anybody have solution?

**Comment by sinyb** [comment]
"Solutions" for now are:
1) DON'T restart Nightly when asked to - will keep you OK until you first have to reboot
2) run Firefox Dev and open tabs from Nightly session (you have set up Firefox account between two, right? So you can switch to something at least half-stable when bleeding-edge goes south... not that I remember when did I have to, but this is a good opportunity)

:)

**Comment by Wolferine69** [comment]
workaround - downgrade FF and disable automatic  updates, profile can be reused after downgrade, just delete compatibility.ini from it

**Comment by gammy** [comment]
> workaround - downgrade FF and disable automatic updates, profile can be reused after downgrade, just delete compatibility.ini from it

Asking just for clarity: to which version is one to downgrade, and where would one obtain said version?

**Comment by huh666** [comment]
i try firefox-131.0a1.en-US.win64.installer.exe from here: https://ftp.mozilla.org/pub/firefox/nightly/2024/08/2024-08-21-16-06-37-mozilla-central/ and it works, dont forget before disable "Automatically install updates (recommended)" in settings menu

**Comment by Wolferine69** [comment]
> > workaround - downgrade FF and disable automatic updates, profile can be reused after downgrade, just delete compatibility.ini from it
> 
> Asking just for clarity: to which version is one to downgrade, and where would one obtain said version?

I am using https://ftp.mozilla.org/pub/firefox/nightly/2024/07/2024-07-09-21-41-33-mozilla-central-l10n/firefox-130.0a1.cs.win64.installer.exe (czech version)

**Comment by GIS1980** [comment]
When I turn Paxmod on, I get the following message in the browser console.  Unsure if it points to anything meaningful:

Unexpected pre-existing callContextData on ""Paxmod" (ID: paxmod@numirias, moz-extension://02f72ee3-243a-476a-a1bd-4676f5a011f0/)" contextId 455

**Comment by by-shiw** [comment]
> i try firefox-131.0a1.en-US.win64.installer.exe from here: https://ftp.mozilla.org/pub/firefox/nightly/2024/08/2024-08-21-16-06-37-mozilla-central/ and it works, dont forget before disable "Automatically install updates (recommended)" in settings menu

it worked on mac, thanks.

**Comment by alen-z** [comment]
Stopped on Developer Edition.

**Comment by sinyb** [comment]
> Stopped on Developer Edition.

Thanks, read this just in time to prevent my Dev from updating.

**Comment by alen-z** [comment]
My new approach is as follows.

userChrome.css
```css
/* 2024-11 */
toolbar#TabsToolbar {
    display: none;
}

/* old */

vbox#titlebar {
    display: none;
}
```

Add sidebar with Simple Tab Groups plugin.

<img width="318" alt="image" src="https://github.com/user-attachments/assets/c5b0202f-218f-4db9-bdfd-81ddec8c8a92">

Edit:
* Use FF UI [debugging mode](https://superuser.com/questions/1608096/how-to-inspect-firefoxs-ui).
* In active root profile directory found in `about:profiles`, place file in `/chrome/userChrome.css`.

**Comment by corang** [comment]
Yeah, confirm stopped working in dev firefox :(

**Comment by adisor19** [comment]
Crap.. i really hope there is a fix for this. I need multiple rows of tabs

**Comment by corang** [comment]
Once you downgrade you can add a `policies.json` file in a folder called `distribution` next to `firefox.exe` that keeps it from asking you to update:
```json
{
    "policies": {
        "AppAutoUpdate": false,
        "AppUpdatePin": "131.",
        "BackgroundAppUpdate": false,
        "DisableAppUpdate": true,
        "ManualAppUpdateOnly": true
    }
}
```
file structure:
```
- firefox.exe
- distribution
   |- policies.json
```
only tested on windows with firefox nightly

**Comment by adisor19** [comment]
Unfortunately, the blocker does not work on macOS with the FireFox Dev edition.. It updates automatically upon restart of Firefox..  If anyone knows how to block it from updating, please share..

**Comment by adisor19** [comment]
UPDATE: I disabled automatic updates and I was able to keep it on Firefox 130.0b9 indefinitly after multiple restarts. In order to downgrade the profile, I was able to do it by starting up 130.0b9 from terminal with this command : cd /Applications/Firefox\ Developer\ Edition.app/Contents/MacOS followed by ./firefox -allow-downgrade

**Comment by fraynaud33** [comment]
Hello, I found tab mix plus is reborn !!!
https://github.com/onemen/TabMixPlus
But this project seems to be more maintained. (last update 08/09/2024 !)
~~But unfortunately It doesn't work on Firefox 131.0b too ;-(
I create [an issue](https://github.com/onemen/TabMixPlus/issues/326), we will see what happen.~~
Edit 10/09/2024 : [the release123](https://github.com/onemen/TabMixPlus/releases/tag/v1.23.0) fix the bug and multi row works now on 131.0b4 !

**Comment by Amarok73** [comment]
> Hello, I found tab mix plus is reborn !!! https://github.com/onemen/TabMixPlus But this project seems to be more maintained. (last update 08/09/2024 !) ~~But unfortunately It doesn't work on Firefox 131.0b too ;-( I create [an issue](https://github.com/onemen/TabMixPlus/issues/326), we will see what happen. ~~ Edit 10/09/2024 : [the release123](https://github.com/onemen/TabMixPlus/releases/tag/v1.23.0) fix the bug and multi row works now on 131.0b4 !

On 131.0b5 I am unable to install this TabMixPlus, as it reports that this addon appears to be corrupt. Anyone can confirm it?
![obraz](https://github.com/user-attachments/assets/a30b9bb6-e8cb-4c52-ac46-6e1763249b9b)

**Comment by Olddddd** [comment]
> Hello, I found tab mix plus is reborn !!! https://github.com/onemen/TabMixPlus But this project seems to be more maintained. (last update 08/09/2024 !) ~But unfortunately It doesn't work on Firefox 131.0b too ;-( I create [an issue](https://github.com/onemen/TabMixPlus/issues/326), we will see what happen.~ Edit 10/09/2024 : [the release123](https://github.com/onemen/TabMixPlus/releases/tag/v1.23.0) fix the bug and multi row works now on 131.0b4 !

But no dynamic color unfortunately. We can still combine both extensions but there are few bugs in doing so.

**Comment by tauon** [comment]
> When I turn Paxmod on, I get the following message in the browser console. Unsure if it points to anything meaningful:
> 
> Unexpected pre-existing callContextData on ""Paxmod" (ID: paxmod@numirias, moz-extension://02f72ee3-243a-476a-a1bd-4676f5a011f0/)" contextId 455

Looks like this is the line that's getting hit: https://searchfox.org/mozilla-central/source/toolkit/components/extensions/ExtensionParent.sys.mjs#656

**Comment by nazar-pc** [comment]
Here is how it was fixed in the extension above: https://github.com/onemen/TabMixPlus/commit/21288e55d2340e0a2e0d170c9e08a4237760908e

**Comment by inthroxify** [comment]
> Hello, I found tab mix plus is reborn !!! https://github.com/onemen/TabMixPlus But this project seems to be more maintained. (last update 08/09/2024 !) ~But unfortunately It doesn't work on Firefox 131.0b too ;-( I create [an issue](https://github.com/onemen/TabMixPlus/issues/326), we will see what happen.~ Edit 10/09/2024 : [the release123](https://github.com/onemen/TabMixPlus/releases/tag/v1.23.0) fix the bug and multi row works now on 131.0b4 !

@fraynaud33 Thank you for finding this and posting here! I could kiss you, I am so happy to see that TMP is still around, I had no idea. I am switching.

@numirias Are you still around?

**Comment by nazar-pc** [comment]
He responded to me last time about 2 years ago on Twitter, but nothing since unfortunately

**Comment by parasiteoflife** [comment]
Someone please make a fork, numirias has not shown public activity for 2 years

**Comment by nazar-pc** [comment]
Looks like it broke even more than before in latest nightly making this extension unusable for me.

https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs.css allows to bring back multi-row-tabs, but not other things. @MrOtherGuy's collection of tweaks is quite extensive and I think they'd be able to fix our issues here, but not sure they have the time or passion for it.

**Comment by MrOtherGuy** [comment]
I'll jump in to say that no, I don't have any interest in maintaining this project, but I can give you some pointers.

I'm pretty sure that the problem that first caused this issue on 2024-08-22 is that your [browser.css line 43](https://github.com/numirias/paxmod/blob/bbb35542eaaed7272eff6c410499cb52d0711d71/src/browser.css#L43) doesn't apply the rules to the correct element anymore. Those style rules should be applied to the child `<slot>` of that element. Unfortunately the way you have set things up (because your browser.css is loaded as author sheet) you cannot target that `<slot>` element. If you went to change your browser.css to be loaded as user_sheet instead, the you would need to rewrite bunch of other things. Another option, although I'm not sure if that is available for you, would be to mark that slot element with a `part` attribute, which you could then use in browser.css in place of that `::part(scrollbox)` (could be for example `::part(scrollbox-slot)` or whatever).

I don't know your project well enough to tell what broke just now in Nightly 133, but the `#titlebar` was wholly removed if any part of your codebase rely on that element being there then it will certainly be broken.

**Comment by aadityaverma** [comment]
Still Broken in Dev Ubuntu.

**Comment by sinyb** [comment]
Well, I have switched to MrOtherGuy's "firefox-csshacks" https://github.com/MrOtherGuy/firefox-csshacks/tree/master just to have back multi-row tabs, and it is working fine in latest Nightly. Yes, I am missing a few good things from here (differrent colors for example), but I only really need multiple rows of tabs, everything else is not so important. 
I am closing this now as "won't fix, go elsewhere"

**Comment by adisor19** [comment]
That's shame as this is honestly the better addon out there.. Oh well. Maybe one day, @numirias will surprise us all with a fix.

**Comment by adisor19** [comment]
I'm not sure how I didn't notice this earlier, but a huge thank you to @PacificViking for his patch! I installed web-ext, cloned his repository that includes that patch, built the extension with make build and installed it and IT WORKS with latest 137b6 as of this writing!

**Comment by parasiteoflife** [comment]
> I'm not sure how I didn't notice this earlier, but a huge thank you to [@PacificViking](https://github.com/PacificViking) for his patch! I installed web-ext, cloned his repository that includes that patch, built the extension with make build and installed it and IT WORKS with latest 137b6 as of this writing!

For me it works with some issues, tab bar is always double line, minimize, maximize and exit buttons are displayed vertically, reordering tabs doesn't work, tabs are a little too big in height

**Comment by adisor19** [comment]
I mean, it's better than not working at all. It does have some glitches but at least it gets the job done.
