### ISSUE TITLE
Settings export/import

### ISSUE THREAD

**Issue by Djagga-Djagga** [numirias/paxmod#13]
Export/import settings in a file for handy crossover between platforms and computers.

**Comment by Djagga-Djagga** [comment]
When i click Import - file choosing window opens, but when I click Export - nothing happens (I suspect same dialog should open with file name input and location choosing)

**Comment by numirias** [comment]
That's odd. It's supposed to open the JSON in a new tab/window which you can then just save.

I suspect that may be related to some popup blocker addon you may be using. But it's more clean to just offer a "save as..." dialog anyway, so I'll change it accordingly.

**Comment by numirias** [comment]
Exporting the settings now immediately triggers a download dialog (see release [v2.3](https://github.com/numirias/paxmod/releases/tag/v2.3)). Does importing and exporting work for you now?

**Comment by Djagga-Djagga** [comment]
Yep, now it works perfectly! Thank you!
But inline titlebar isn't look like a good thing - I'll open other issue to show you
