### ISSUE TITLE
Tab dragging

### ISSUE THREAD

**Issue by Djagga-Djagga** [numirias/paxmod#15]
It seems there is some trouble in dragging tabs from top to bottom row (from bottom to top works well for me)

**Comment by numirias** [comment]
I spent some time on this one and I couldn't find a CSS-only way to get tab dragging with multi-row tabs fixed. So for now I just added [a section](https://github.com/numirias/paxmod#dragging-tabs-around-isnt-smooth) to the README which hints at some keyboard shortcuts you may want to use instead - at least that's how I do it.

If someone knows how to get that patched, let me know.

**Comment by numirias** [comment]
The latest release has some custom JS (sigh...) that should enable proper tab dragging across rows.
