### ISSUE TITLE
Variables rename (make it more understandable)

### ISSUE THREAD

**Issue by Djagga-Djagga** [numirias/paxmod#16]
I also suggest you to rename and make more obvious names used (like toolbar_top_separator or Default tab sixe10% or Min tab color lightness etc.) to make it more clear what are exactly changing (it is ok to remove redundant ones that doen't change any visible things). E.g. "Active Tab", "Hovered Tab", "Address line background color", "Toolbar button hovered" or something like this. Or make any popups to explain it.
As for me ( http://prntscr.com/jklqc8 ), for example, I would like to change color of separator on Bookmarks toolbar, as it is looks a bit messy, and separator is just invisible. I'm not a developer, so I can't really guess which value I need to change or address it directly via css styles etc...

**Comment by numirias** [comment]
I agree the color variable names are somewhat unintuitive. But the rationale behind that is to use the same names as Mozilla uses on its theme API. (That also makes it easier for people familiar with writing themes to associate them.)

Did you find [this document on MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme#colors)? It explains each color variable plus screenshots.

I'll make sure I'll link more directly to that document.

>  I would like to change color of separator on Bookmarks toolbar

Do you mean the line between the bookmarks and the urlbar?

**Comment by numirias** [comment]
- In most cases MDN does explain the variables pretty well, so I just added very few explanatory notes to the settings page.
- There are no "unused" colors anymore.
- I tweaked the CSS a bit, so your UI should look a bit more compact and consistent now.
