### ISSUE TITLE
Update using newer type of WebExtension Experiments

### ISSUE THREAD

**Issue by nt1m** [numirias/paxmod#2]
WebExtensions Experiments are now inlined with the WebExtension itself.

See https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/basics.html#webextensions-experiments

Old WebExtension Experiments will be removed in Firefox 61.

**Comment by numirias** [comment]
Thanks, that's great to know!

I'll update accordingly ASAP.

**Comment by numirias** [comment]
Thanks again for the hint. This has also made installation steps much easier.

**Comment by nt1m** [comment]
Thanks! Just wanted to say it works pretty nicely on macOS:
<img width="988" alt="screen shot 2018-05-02 at 1 49 39 pm" src="https://user-images.githubusercontent.com/1795135/39524059-b483bef8-4e0f-11e8-86eb-845653d82a75.png">

Only problem is that Firefox tabs in titlebar code doesn't work well with the multi-row tabs when resizing the window.

**Comment by nt1m** [comment]
@numirias Btw, would you be interested in writing a WebExtension experiment for [bug 1320585](https://bugzilla.mozilla.org/show_bug.cgi?id=1320585) ? The API has been approved by Mozilla, so I can help you get it integrated in Firefox if you're interested.

**Comment by numirias** [comment]
> Only problem is that Firefox tabs in titlebar code doesn't work well with the multi-row tabs when resizing the window.

Thanks for pointing out. I'll see if I can get my hands on a mac and troubleshoot this.

Regarding writing the experiment - I'm afraid I'm really not that experienced with JS and FF internals to work on this. :/ I just barely managed to put this small add-on together. But I'll definitely follow the ticket, would be great to have tab colors via an approved API.
