### ISSUE TITLE
Tab colors based on the current domain

### ISSUE THREAD

**Issue by cbertoldi** [numirias/paxmod#20]
Hi numirias,

I am wondering if it would be possible to integrate into paxmod the functionality of Colorful Tabs prior to the introduction of Firefox Quantum. Basically what I would like to be able to do, is specifying a tab background color based on the current domain. This is very helpful for me, to quickly distinguish between different environment, e.g. testing vs production.

I also tried installing an older version of Colorful Tabs the same way I had to install paxmod, but the xpi was classified as corrupted.

I know this might not be the right place to discuss such problems, but I did not find another way to contact you.

Thank you for your time.

**Comment by numirias** [comment]
Thanks for reaching out. I can totally see why you'd want this.

But unfortunately I don't see a convenient way to implement that with the current design. Right now, Paxmod works with CSS selectors (which keeps the API small), along the lines of:

```css
.tabbrowser-tab .tab-icon-image[src=FAVICON_URL] ~ .tab-label-container .tab-label { color: CALCULATED_COLOR !important; }
```

However, the current domain is not set as an attribute anywhere in the tab element's DOM subtree, so I can only distinguish between favicon URLs, not domains.

The good news is that there may be an API for individual tab colors coming ([bug 1320585](https://bugzilla.mozilla.org/show_bug.cgi?id=1320585)) which would allow me to conveniently apply colors based on domains etc. But for now I'm afraid it's not possible.

**Comment by cbertoldi** [comment]
Thank you very much.
I've already knew that Firefox Bug Ticket because of ColorfulTabs. I really miss this extension for my working habits.
I had a little hope because in order to use Paxmod I have to enable the legacy extensions, but I guess that Mozilla just removed the API on which ColorfulTabs was based.
For the moment as  workaround I've started using the Tree Style Tab RainbowTabsFork, just in case anybody else should have my problem.

**Comment by numirias** [comment]
Won't be looking into this for now.
