### ISSUE TITLE
Close tab button

### ISSUE THREAD

**Issue by Djagga-Djagga** [numirias/paxmod#22]
Hi again!

After complete reinstall of macos I reinstalled firefox and paxmod as well, inporting all settings.
But since enabling Paxmod tabbar changes properly but the "X" button completely disappears from all and every tab (http://prntscr.com/kadto0)
I tried several advice from internet - but nothing works. Any help?

**Comment by numirias** [comment]
@Djagga-Djagga  Sorry for getting back to this a bit late. After an update of Nightly I can reproduce the issue and will supply a patch ASAP.

**Comment by numirias** [comment]
@Djagga-Djagga Thanks for making me aware of the issue! It's fixed in [v2.6](https://github.com/numirias/paxmod/releases/tag/v2.6). Feel free to confirm. :)

**Comment by Djagga-Djagga** [comment]
Worked like charm, thank you!
