### ISSUE TITLE
Custom CSS not functions

### ISSUE THREAD

**Issue by wandbrandon** [numirias/paxmod#24]
For some reason, even when I put the directory or try to import it in the custom css box, it doesn't seem to grab the colors. Oddly enough, it takes my gtk colors when I set the theme default in Firefox's customize page.

**Comment by wandbrandon** [comment]
Yeah works just fine. Might have something to do with my css file? Comes from pywal which works normally in most cases.

**Comment by numirias** [comment]
I think I can reproduce that. Imported sheets are loaded, but somehow the color variables don't seem to be picked up.

They work however, when you just paste the file content into the *Custom CSS* text box, e.g.:

```css
:root {
  --background: red;
}
```

I'll look into that.

**Comment by wandbrandon** [comment]
Yep, works when pasting the code in the textbox.

**Comment by numirias** [comment]
Unfortunately, theming capabilities won't be part of Paxmod anymore. (Also see #33)
