### ISSUE TITLE
Disable switching tab with the mouse wheel

### ISSUE THREAD

**Issue by The-Phi** [numirias/paxmod#29]
There's a feature that I'm not used to and I'd prefer to not have it actually: It is the "tab switching thanks to the mouse wheel":
If you position the mouse pointer on a tab title, and then use the mouse wheel, you will switch immediately from one tab to another (in a circle).
How can I disable it? Thanks a lot in advance

**Comment by numirias** [comment]
This is a feature of Firefox, not Paxmod. You should be able to verify that by disabling Paxmod and checking if the behavior is still present.

This may be relevant: https://bugzilla.mozilla.org/show_bug.cgi?id=1285812
