### ISSUE TITLE
Problems in FF Nightly 61.0a1 (2018-05-01) (64-bit)

### ISSUE THREAD

**Issue by icejr** [numirias/paxmod#3]
_**Hello Dev**_,

I'm currently facing two problems with installation guide. I'm using _Nightly 61.0a1 (2018-05-01) (64-bit)_ on _Windows 10 1803 (30 April's Update)_. I enabled legacy extensions and disabled extension signature checks.

1st problem is Nightly says **Stylesheet API** (stylesheet-api-expiment-1.0.xpi) is **corrupt and could not be installed**.

2nd one is **Paxmod** (paxmod-1.3.xpi) is **not compatible with** **Nightly 61.0a1**.

I'm seriously **_dying_** to try out this awesome theme.

With love,
_**Kaiser**_.

**Comment by numirias** [comment]
Thanks for reporting!

This is almost certainly related to #2. (Since FF61 Firefox uses a different format for API experiments.)

I'm making an update ASAP.

**Comment by numirias** [comment]
I made a new release. You should now be able to use the addon in FF 61+.

Note that the installation instructions also changed a bit (it's now much easier, no need to install two separate extensions anymore).

On a side note, I never tested paxmod on Windows, so I'm really curious if it looks the same as in the demo gifs I made on Linux, or if you get a lot of design glitches. If you find the time I'd love some feedback on that!
