### ISSUE TITLE
Future of Paxmod

### ISSUE THREAD

**Issue by numirias** [numirias/paxmod#33]
A couple of notes, in case you're using Paxmod:

Since Firefox regularly introduces UI changes that require patches in Paxmod, it's quite time-consuming to keep the add-on working. Therefore, in the [new releases](https://github.com/numirias/paxmod/releases), I'm just focusing on the few core features and I've dropped a lot of other stuff - most of which was implemented at a time where the default UI was more painful to use and the available WebExtensions APIs weren't very powerful.

What stays:
- Multiple tab rows
- Site-dependent tab colors
- Some customization knobs (and the ability to add custom CSS)

What's gone:
- UI tweaks, theming and color settings. By now, Firefox has a pretty good theme infrastructure and makes it easy to [build your own themes](https://color.firefox.com/). Also, rearranging stuff and changing the UI density under *Customize* works pretty well anyway.

(FWIW, I've also started working on [a small add-on](https://github.com/numirias/firefox-theme-tweak) to customize themes ad-hoc, so if you're missing the ability to quickly adjust colors in the settings, maybe that'll help (once it's done).)

**Comment by nt1m** [comment]
@numirias The `theme_experiment` feature should make it easier to maintain your extension in case you haven't seen it:

```json
{
  "manifest_version": 2,
  "name": "Theme experiment",
  "description": "Example of a theme experiment",
  "version": "1.0",
  "theme": {
    "colors": {
      "popup_affordance": [128,128,128]
    },
    "images": {
      "theme_toolbar": "toolbar.jpg"
    }
  },
  "theme_experiment": {
    "stylesheet": "style.css",
    "colors": {
      "popup_affordance": "--arrowpanel-dimmed"
    },
    "images": {
      "theme_toolbar": "--toolbar-bgimage"
    },
    "properties": {
      "toolbar_image_alignment": "--toolbar-bgalignment"
    }
  }
}
```

The `style.css` stylesheet can be used to style those properties too:
```css
#nav-bar {
   background-position: var(--toolbar-bgalignment);
}
```

You can then use the new properties you just defined in extension code too:

```js
browser.theme.update({
  colors: {
    popup_affordance: "green",
  }
});
```

**Comment by nt1m** [comment]
Also, note that's there's a bug affecting theme_experiment that causes the experiment to only apply in the initial window it's loaded in, which has been fixed in Firefox 68: https://bugzilla.mozilla.org/show_bug.cgi?id=1482870

**Comment by Ladergorn** [comment]
Unfortunately Paxmod seems to be broken with 71.0a1 (2019-10-04) (64-bit). I'm not getting multi-row tabs anymore.
Thanks

**Comment by numirias** [comment]
@Ladergorn I issued an update (v3.2). Just go to `about:addons` and *Paxmod* > *Check for Updates*.

**Comment by Ladergorn** [comment]
Cheers - many thanks! Working great again!
