### ISSUE TITLE
New tab ("+") tool always on its own line

### ISSUE THREAD

**Issue by The-Phi** [numirias/paxmod#34]
Since the last update today (it's now version 66.0b2 (64-bits) I've noticed a change in the tab sections:
Before, the New Tab ("+") tool to open new tab was in continuity of the tabs just before, on the same line.
I've received an update today apparently (I had to restart Firefox dev) (now it's 66.0b2 (64-bits)):

![image](https://user-images.githubusercontent.com/32409014/52537247-b9481800-2d64-11e9-9273-a24510b4a527.png)

and this is what happens with the New tab ("+") tool. Even though the tab line is not full, the "+" is always on its own line.

**Comment by numirias** [comment]
Please have a look at #33. The latest version of Paxmod is only compatible with FF67+ (which you can get as Nightly right now, but have to wait until March if you want it in Developer). I'm not planning to look into issues for older versions, so I'm afraid you need to wait and maybe disable the new tab button in the settings until then.

If you get that issue with latest Paxmod and FF67+, you're obviously welcome to reopen the issue.
