### ISSUE TITLE
Top 1px of Title Bar Doesn't Highlight Tab Beneath It

### ISSUE THREAD

**Issue by M1ch431** [numirias/paxmod#36]
To clarify the title, I'm talking about when a window is maximized (on Windows); when you place your mouse cursor at the very top of the screen directly above the tab you want to click.
Thanks for your hard work on this addon. Feel free to close this issue if it isn't possible to fix. Much love.

EDIT: This can be fixed by setting the tab height to 29, but maybe this could be fixed for the default height?

**Comment by numirias** [comment]
Well, a few years later I went ahead and made 29px the minimum tab height, so I hope this doesn't occur anymore. (See release v3.8)
