### ISSUE TITLE
I cannot install it. Firefox keep preventing installation

### ISSUE THREAD

**Issue by SanderBouwhuis** [numirias/paxmod#37]
Because this extension is unsigned I cannot install it. Very frustrating.
I even set the 'xpinstall.signatures.required' option to false, but that still doesn't work.

I'm really desperately looking for multi-row tabs feature.

Help, help, help!

**Comment by numirias** [comment]
- Which FF version are you using?
- Did you exactly follow the [installation instructions](https://github.com/numirias/paxmod#installation)?
- If so, please go to `about:support` and paste the content here.

**Comment by SanderBouwhuis** [comment]
Aha! I did not activate the 'allow legacy addons' option.
Sorry about that.

Anyway, I already got it working with this:
https://github.com/MrOtherGuy/firefox-csshacks
