### ISSUE TITLE
Multi-row broken on newest nightly

### ISSUE THREAD

**Issue by syndesis** [numirias/paxmod#39]
I just updated my nightly and multi-row is broken.

FF Nightly 71.0a1 (2019-10-03) (64-bit)
OSX High Sierra 10.13.6

<img width="835" alt="Screen Shot 2019-10-03 at 11 07 40 AM" src="https://user-images.githubusercontent.com/611764/66148415-0fa4e800-e5ce-11e9-8e59-ab3381c8bcca.png">

**Comment by olaims** [comment]
same here with the 71.0a1 (64-bit)
Windows 10

**Comment by furuboru** [comment]
Same here! Windows 10 on FF 71.0a1 (x64). The problem posted by syndesis really only happens on windows with a lot of tabs. Other browser windows with only 3~5 open tabs don't seem to be affected...

**Comment by numirias** [comment]
Sigh, what did Mozilla do this time... I'm looking into this today. Thanks for the heads-up!

**Comment by numirias** [comment]
@syndesis @olaims @furuboru The recent update should do the trick.

You also shouldn't need to install the new version via Github. Just go to `about:addons` and click *Check for Updates*. Also, let me know in case you still have problems.

**Comment by syndesis** [comment]
Looks good, thanks!

**Comment by furuboru** [comment]
It's aaallliiiivveeeee! Thanks so much! Multi-row tabs are back!
