### ISSUE TITLE
tab width (and other parameters) doesn't work anymore in FF developer 72.0b3 (64 bits)

### ISSUE THREAD

**Issue by fraynaud33** [numirias/paxmod#47]
Hello,
I think it's since the last update of my Firefox Developer Edition 72.0b3 (64 bits) that paxmod custom style doesn't work. My tab are with large width and if I change parameter in option (min/maw width, font;..) no change on the UI.
Thanks for the help.
![image](https://user-images.githubusercontent.com/26875828/70380271-95c80c80-1938-11ea-9d83-a36092c0f940.png)

**Comment by Delta2401** [comment]
Yeah, the tab width seems to now cap around the amount of space the tab title takes up; except for the bottommost row, for whatever tabs take up, they stretch. As a passerby, I would just rename tabs to be shorter titles and take less room; while waiting for a better fix if we can get it.

**Comment by 090media** [comment]
I probably don't need to emphasize this, but since no one did yet-- This totally breaks Paxmod for many users (myself included). Commonly have 70 or 80 tabs open at one time. This is the main reason I went looking for a solution in the first place and found Paxmod. 70 or 80 tabs with no width limit means the entire browser window is tabs. Any word from the great and powerful Numirias as to when there might be a fix or even a workaround?

**Comment by xeonight** [comment]
TEMPORARY FIX: if you go to options, in the 'custom CSS' window, you add this:

.tabbrowser-tab {
   /* This fixes the issue of the tabs expanding to the FULL title in Firefox 72 and causing too many rows, set this to whatever size you want, it overrides the size option above */
  width: 106px !important;

  /* this fixes the tabs expanding to fill the bar regardless of the above options */
  flex-grow: 0  !important; 
}

**Comment by fraynaud33** [comment]
> 
> 
> TEMPORARY FIX: if you go to options, in the 'custom CSS' window, you add this:
> 
> .tabbrowser-tab {
> /* This fixes the issue of the tabs expanding to the FULL title in Firefox 72 and causing too many rows, set this to whatever size you want, it overrides the size option above */
> width: 106px !important;
> 
> /* this fixes the tabs expanding to fill the bar regardless of the above options */
> flex-grow: 0 !important;
> }

Thanks, it works !

**Comment by Delta2401** [comment]
> 
> 
> TEMPORARY FIX: if you go to options, in the 'custom CSS' window, you add this:
> 
> .tabbrowser-tab {
> /* This fixes the issue of the tabs expanding to the FULL title in Firefox 72 and causing too many rows, set this to whatever size you want, it overrides the size option above */
> width: 106px !important;
> 
> /* this fixes the tabs expanding to fill the bar regardless of the above options */
> flex-grow: 0 !important;
> }

Thank you, it works. But why is this fix marked temporary? It seems to be working fully.

**Comment by xeonight** [comment]
> 
> 
> > TEMPORARY FIX: if you go to options, in the 'custom CSS' window, you add this:
> > .tabbrowser-tab {
> > /* This fixes the issue of the tabs expanding to the FULL title in Firefox 72 and causing too many rows, set this to whatever size you want, it overrides the size option above */
> > width: 106px !important;
> > /* this fixes the tabs expanding to fill the bar regardless of the above options */
> > flex-grow: 0 !important;
> > }
> 
> Thank you, it works. But why is this fix marked temporary? It seems to be working fully.

It is temporary because it overrides one of the settings in Paxmod, yes you can use it this way just fine, but the addon itself needs to be changed so that this problem doesn't happen in the first place (if possible) and I have nothing to do with the development of this addon, i just browsed a couple files and tried a couple changes until i found the setting that fixed the problem, e.g. temporary :)

**Comment by syndesis** [comment]
> TEMPORARY FIX: if you go to options, in the 'custom CSS' window, you add this:
> 
> .tabbrowser-tab {
> /* This fixes the issue of the tabs expanding to the FULL title in Firefox 72 and causing too many rows, set this to whatever size you want, it overrides the size option above */
> width: 106px !important;
> 
> /* this fixes the tabs expanding to fill the bar regardless of the above options */
> flex-grow: 0 !important;
> }

@xeonight Where is the Custom CSS window?

**Comment by numirias** [comment]
Sorry guys, I've been on Christmas vacation. Thanks for investigating.

I released a new version which should fix this issue. You should receive the update automatically once your FF checks for updates.

**Comment by fraynaud33** [comment]
Thanks for your work and for your quick fix. It works perfectly.
Very good job to add this feature (hard to maintain visibly) to firefox.
