### ISSUE TITLE
First pinned tab is not displayed, when window is maximized.

### ISSUE THREAD

**Issue by jtagcat** [numirias/paxmod#49]
**Describe the bug**
Please clearly describe the bug and how it can be reproduced. Add screenshots, if necessary.
Not maximized:
![Screenshot from 2019-12-28 19-23-33](https://user-images.githubusercontent.com/38327267/71547344-e4485400-2996-11ea-83ee-bcac25fcbe4d.png)
Window is maximized:
![Screenshot from 2019-12-28 19-23-15](https://user-images.githubusercontent.com/38327267/71547342-de527300-2996-11ea-8719-5c8cf3220b72.png)

**Environment**
State your OS, Firefox, Paxmod version, etc. (You can just go to `about:support` and paste the information here.)
Fedora 31, Firefox 72.0b11 (20191227034945), 
Paxmod settings:
```
"displayCloseButton": false,
"displayNewtab": false,
"displayPlaceholders": false,
"displayTitlebar": true,
"enableIconColors": false,
"fontFamily": "inherit",
"fontSize": "15",
"maxLightness": "100",
"maxTabSize": "60",
"minLightness": "59",
"minTabHeight": "28",
"minTabSize": "60",
"roundedCorners": true,
"tabSize": "10",
"userCSS": "",
"userCSSCode": ""
```

**Comment by furuboru** [comment]
So this happened to me as well, what worked was disabling paxmod then maximizing affected windows (or those with pinned tabs), re-enabling paxmod, restoring windows to float, and just kept on doing that until it got fixed. And they did!

**Comment by jtagcat** [comment]
yeah but doing this much work for every time you maximize is unreasonable
it sometimes fixes itself
..and sometimes brakes again by itself
I don't really care myself, since I use keyboard shortcuts to access pins anyways.

**Comment by furuboru** [comment]
So my FF crashed, and when I restarted it that hack above didn't work anymore.... what did work was having about 10 tabs pinned, then the first pinned tab pops out when you resize the window. Worked every time on this other window with 10 tabs, so maybe that was the sweet spot for my tab-width configuration.

But yes, not having to jump over hoops every time you load up FF would be very nice. :D

**Comment by jtagcat** [comment]
to add to the problem, a tab worth of space is not used
![image](https://user-images.githubusercontent.com/38327267/77917637-56784f80-728a-11ea-8217-f49d94873c61.png)

**Comment by jtagcat** [comment]
Workaround when using Gnome:
`org.gnome.desktop.wm.preferences button-layout`: It probably has something on the left side, in my case it had appmenu (`appmenu:close`).

Setting it to `:appmenu,close` (moving appmenu to the right side) gets rid of the issue.

**Comment by numirias** [comment]
The latest release should fix this. Have a look! :)

**Comment by jtagcat** [comment]
Had a look, :tada:
