### ISSUE TITLE
Multi-row broken in 74.0a1 (2020-01-16)

### ISSUE THREAD

**Issue by syndesis** [numirias/paxmod#50]
After restarting on 2020-01-16 nightly, I only get a single row of horizontally scrolling tabs.

**Environment**
OS: OSX
Firefox: 2020-01-16 nightly

**Comment by numirias** [comment]
Thanks, looking into it right now.

**Comment by numirias** [comment]
It seems Firefox introduced a new config setting you need to enable. Could you check if this works:

- Go to `about:config` and set `extensions.experiments.enabled` to `true`.
- Disable and re-enable Paxmod.

**Comment by syndesis** [comment]
Yep, that works. Thanks!
