### ISSUE TITLE
Does paxmod have some way to get how many tabs are on each row from outside the extension?

### ISSUE THREAD

**Issue by jtagcat** [numirias/paxmod#51]
So I'm soon forking an extension what prepends a tiny number for each tab (for use with `Ctrl`/`Alt`+`num`). As a new feature, selecting a row and then a tab within it would be 2 extensions of paxmod.
Can I somehow get what tab is in what row in what position of the row?

**Comment by numirias** [comment]
The tab sizing and wrapping is pure CSS, so the addon doesn't really know what tab is where. You could either determine positions with JS (however, this addon can't access the UI with JS, and I want to keep it that way), or, possibly, implement the flexbox sizing algorithm yourself and then calculate where a tab is supposed to be.
