### ISSUE TITLE
Paxmod broken

### ISSUE THREAD

**Issue by Ladergorn** [numirias/paxmod#52]
My Firefox Dev has upgraded to 74.0b3 (64-bit) 20200214015126 and sadly no more multi row tabs.

**Comment by numirias** [comment]
Thanks for reporting. Did you check https://github.com/numirias/paxmod/issues/50?

**Comment by Ladergorn** [comment]
I hadn't seen that comment. Paxmod now working again - many thanks, you are the BOSS!
