### ISSUE TITLE
Multi-Row Broken Again [As of March 30th-2020 FF Nightly Update]

### ISSUE THREAD

**Issue by Delta2401** [numirias/paxmod#53]
Summary: Tab resizing works this still, but won't move to another row.

Details: Hit the update firefox button, and when it restarted, all tabs were on one line again. Did some tinkering with the CSS fixes before, and noticed all the tab width options do seem to work. It's just they all get stuck on the same row anyway. I double checked the config to make sure the experimental values were still checked as true; and they are. Not sure where to go from here.

Windows 10 Pro x64, FF Nightly 76.0a1 (2020-03-30)
Also tested on: FF Nightly 76.0a1 (2020-03-31) (64-bit) - so no change in overnight.

**Comment by jtagcat** [comment]
I would suggest an edit to the title to include Nightly, also see #54

**Comment by olaims** [comment]
same here

**Comment by olaims** [comment]
> 
> 
> I would suggest an edit to the title to include Nightly, also see #54

It's not necessary anymore to use a Nightly version for paxmod ?

**Comment by jtagcat** [comment]
> > I would suggest an edit to the title to include Nightly, also see #54
> 
> It's not necessary anymore to use a Nightly version for paxmod ?

Comments about #54 go to #54. Please also stop commenting 'same' on issue trackers and forums, use the +1 instead.

**Comment by jtagcat** [comment]
The update has now reached development edition - almost all users are affected.

**Comment by fraynaud33** [comment]
Same Issue for me with 76.0b2

**Comment by jtagcat** [comment]
> Same Issue for me with 76.0b2

76 breaks paxmod multitab. Please stop commenting 'me too', instead press the :+1: on the original comment.

**Comment by numirias** [comment]
Sorry for the delay, should be fixed. (If you want to help out yourself, I always appreciate a PR for bugs like these.)

**Comment by jtagcat** [comment]
> Sorry for the delay, should be fixed. (If you want to help out yourself, I always appreciate a PR for bugs like these.)

It was on my todo to familiarize myself with the code, I have some experience with add-ons, but none with the ones modifying display elements.
