### ISSUE TITLE
Firefox normal edition supported!

### ISSUE THREAD

**Issue by jtagcat** [numirias/paxmod#54]
So I noticed this and wanted to test:
Clean profile:
![image](https://user-images.githubusercontent.com/38327267/78037497-2d73bf80-735b-11ea-885c-91cc94b697c2.png)

**Comment by olaims** [comment]
Hi @jtagcat , how do you achieve it?

**Comment by olaims** [comment]
When I try it I get this

![image](https://user-images.githubusercontent.com/27026293/78710870-5de8ca00-7916-11ea-9926-64387cdc5353.png)

**Comment by jtagcat** [comment]
Did you try changing the mentioned about:config variables?

If yes, you might have an old profile.

**Comment by olaims** [comment]
I've deleted and created a new firefox profile, and same error.

**Comment by jtagcat** [comment]
> Did you try changing the mentioned about:config variables?

Did you?

Also did you use the profile manager? What version of browser?

**Comment by olaims** [comment]
the about:config variables are as the readme says.

I used about:profiles to create a new profile and to try to install the paxmod from there.

The version of the browser is 75.0

**Comment by jtagcat** [comment]
I'm on latest, 74.0.1 (64-bit). Will see what happens when the next update reaches me.

**Comment by jtagcat** [comment]
I did some developer magic and got myself 75. It seems that paxmod does not work on 75. I suspect, that paxmod working on 74 might've been a bug (from browser security perspective), I'll look in to it.

**Comment by jtagcat** [comment]
Also with my research, I'll note that need to do PR to mention that ESR is supported as well.

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by jtagcat** [comment]
I'll also look in to, if we can sign this outside of AMO, removing the requirement of `xpinstall.signatures.required` = `false`

**Comment by jtagcat** [comment]
Confirmed. Security bug, only works in stable 74. Branching other discussion in to new issues.

Thanks @olaims for pointing this out.
