### ISSUE TITLE
Doesn't work on FF Developer v76.0b4

### ISSUE THREAD

**Issue by numpa** [numirias/paxmod#61]
After update to v76.0b4 from some older version all tabs now in one line. I've checked about:config for correct settings and they are there. Paxmod v3.4. Tried to remove any customizations from chrome folder but to no avail.

**Comment by numirias** [comment]
Thanks for the report. I can't reproduce the problem with the info you provided. Please use the [bug report template](https://github.com/numirias/paxmod/issues/new?assignees=&labels=&template=bug_report.md&title=).

**Comment by numpa** [comment]
What additional info do you need?  I use Win10 Pro 1909.

Application Basics
------------------
Name: Firefox
Version: 76.0b4
Build ID: 20200412214314
Update Channel: aurora
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
OS: Windows_NT 10.0
Launcher Process: Enabled
Multiprocess Windows: 1/1 Enabled by default
Remote Processes: 10
Enterprise Policies: Inactive
Safe Mode: false

Enabled Extensions
--------------------
Name: Adblock Plus - free ad blocker
Version: 3.8.4

Name: AdBlocker for YouTube™
Version: 0.3.2

Name: AdBlocker for YouTube™ Video
Version: 0.1.5

Name: Add Last Active Class To Tab
Version: 1.1

Name: Amazon.com
Version: 1.1

Name: Auto-Sort Bookmarks
Version: 3.4.1

Name: Behind The Overlay
Version: 0.1.6

Name: Bing
Version: 1.1

Name: Bookmark Tab Here
Version: 1.0

Name: Bookmark Tree for Tree Style Tab
Version: 4.1

Name: Canvas Defender
Version: 1.1.0

Name: Disconnect
Version: 5.19.3

Name: Download Master
Version: 3.13.0

Name: DownThemAll!
Version: 4.2.6

Name: DuckDuckGo
Version: 1.0

Name: eBay
Version: 1.0

Name: enable-selection
Version: 1.5

Name: Flagfox
Version: 6.1.25

Name: FoxyProxy Standard
Version: 7.4.3

Name: Google
Version: 1.0

Name: Google Translator for Firefox
Version: 3.0.3.3

Name: Multiple Tab Handler
Version: 3.1.2

Name: Multirow Bookmarks Toolbar Plus
Version: 1.10

Name: NoSquint Plus
Version: 62.1

Name: nURL Suffix
Version: 0.52

Name: Paxmod
Version: 3.4

Name: Pure URL
Version: 1.3.0a

Name: QuickDrag
Version: 2.1.3.23.1-signed.1-signed

Name: ResizeIT 2
Version: 2.0.0

Name: RightToClick
Version: 2.9.6

Name: Save File to
Version: 2.5.5

Name: Save Page WE
Version: 17.2

Name: Scrollbar Search Highlighter
Version: 1.62.1-signed.1-signed

Name: Search by Image
Version: 2.2.0

Name: Select After Closing Current
Version: 4.3

Name: Simple URL Extender
Version: 2.0

Name: Tab Mix - Links
Version: 0.1.0

Name: Tab Session Manager
Version: 6.0.0

Name: Theme Font & Size Changer
Version: 62.0

Name: Twitter
Version: 1.0

Name: Update bookmark
Version: 1.5.0

Name: Video DownloadHelper
Version: 7.3.9

Name: WEAlias
Version: 1.7

Name: Wikipedia (en)
Version: 1.0

Name: Yandex
Version: 1.0

Name: YouTube Video and Audio Downloader (Dev Edt.)
Version: 0.9.1

Name: Zoom Page WE
Version: 17.2

Important Modified Preferences
------------------------------
accessibility.browsewithcaret_shortcut.enabled: false
accessibility.lastLoadDate: 1495261324
accessibility.tabfocus_applies_to_xul: true
accessibility.typeaheadfind: true
accessibility.typeaheadfind.enablesound: false
accessibility.typeaheadfind.flashBar: 0
accessibility.typeaheadfind.timeout: 10000
accessibility.warn_on_browsewithcaret: false
browser.contentblocking.category: standard
browser.display.background_color: #CCCCCC
browser.display.use_system_colors: true
browser.download.folderList: 2
browser.link.open_newwindow.restriction: 0
browser.places.importBookmarksHTML: false
browser.places.importDefaults: false
browser.places.leftPaneFolderId: -1
browser.places.migratePostDataAnnotations: false
browser.places.smartBookmarksVersion: 8
browser.places.updateRecentTagsUri: false
browser.search.openintab: true
browser.search.useDBForOrder: true
browser.sessionstore.max_tabs_undo: 500
browser.startup.homepage: about:blank
browser.startup.homepage_override.buildID: 20200412214314
browser.startup.homepage_override.mstone: 76.0
browser.startup.page: 3
browser.tabs.closeWindowWithLastTab: false
browser.tabs.drawInTitlebar: false
browser.tabs.insertAfterCurrent: true
browser.tabs.insertRelatedAfterCurrent: false
browser.tabs.onTop: false
browser.tabs.remote.autostart.2: true
browser.tabs.selectOwnerOnClose: false
browser.tabs.tabMaxWidth: 300
browser.urlbar.autoFill: false
browser.urlbar.doubleClickSelectsAll: true
browser.urlbar.matchBuckets: general:5,suggestion:Infinity
browser.urlbar.placeholderName: Google
browser.urlbar.searchSuggestionsChoice: false
browser.urlbar.trimURLs: false
browser.urlbar.userMadeSearchSuggestionsChoice: true
browser.zoom.siteSpecific: false
dom.allow_scripts_to_close_windows: true
dom.apps.lastUpdate.buildID: 20161019084923
dom.apps.lastUpdate.mstone: 49.0.2
dom.apps.reset-permissions: true
dom.disable_window_status_change: false
dom.event.contextmenu.enabled: false
dom.ipc.plugins.enabled.npietab2.dll: true
dom.ipc.plugins.flash.disable-protected-mode: true
dom.ipc.plugins.reportCrashURL: false
dom.max_chrome_script_run_time: 60
dom.max_script_run_time: 1800
dom.mozApps.used: true
dom.w3c_touch_events.expose: false
extensions.checkCompatibility.3.5: true
extensions.checkCompatibility.3.6: true
extensions.lastAppVersion: 76.0
general.autoScroll: false
general.useragent.extra.microsoftdotnet: (.NET CLR 3.5.30729)
layers.mlgpu.sanity-test-failed: true
media.benchmark.vp9.fps: 185
media.benchmark.vp9.versioncheck: 1
media.gmp-eme-adobe.abi: x86-msvc-x64
media.gmp-eme-adobe.version: 17
media.gmp-gmpopenh264.abi: x86_64-msvc-x64
media.gmp-gmpopenh264.version: 1.8.1.1
media.gmp-manager.buildID: 20200412214314
media.gmp-widevinecdm.abi: x86_64-msvc-x64
media.gmp-widevinecdm.version: 4.10.1582.2
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.failed: false
plugin.importedState: true
plugin.load_in_parent_process.application/ietab2: true
plugin.state.anti_banner_native_proxy: 2
plugin.state.npauthz: 2
plugin.state.npcontentblocker: 2
plugin.state.npctrl: 2
plugin.state.npdeployjava: 0
plugin.state.nponlinebanking: 2
plugin.state.nppdfxcviewnpplugin: 2
plugin.state.npspwrap: 2
plugin.state.npvkplugin: 2
plugin.state.url_advisor: 2
privacy.cpd.cache: false
privacy.cpd.cookies: false
privacy.cpd.extensions-nosquint: false
privacy.cpd.extensions-tabmix: false
privacy.cpd.sessions: false
privacy.donottrackheader.enabled: true
privacy.popups.showBrowserMessage: false
privacy.purge_trackers.date_in_cookie_database: 0
privacy.sanitize.migrateClearSavedPwdsOnExit: true
privacy.sanitize.migrateFx3Prefs: true
privacy.sanitize.pending: [{"id":"newtab-container","itemsToClear":[],"options":{}}]
privacy.userContext.enabled: true
privacy.userContext.extension: multipletab@piro.sakura.ne.jp
privacy.userContext.longPressBehavior: 2
privacy.userContext.ui.enabled: true
security.dialog_enable_delay: 0
security.disable_button.openCertManager: false
services.sync.declinedEngines:
services.sync.engine.prefs.modified: false
svg.context-properties.content.enabled: true

Important Locked Preferences
----------------------------
dom.ipc.processCount.webIsolated: 1
fission.autostart: false

**Comment by numirias** [comment]
Does the extension not install/can't be enabled at all? Or does it just not change the UI?

**Comment by numirias** [comment]
Strange. Could you double-check the value of `layout.css.shadow-parts.enabled`?

**Comment by numpa** [comment]
> The addon installs, but just doesn't have any effect, right?
Exactly. It worked perfectly before update.

**Comment by syndesis** [comment]
@numpa I believe Paxmod 0.34 won't work on that version of Firefox.  Can you try 0.33?

**Comment by numirias** [comment]
I can successfully run Paxmod 3.4 on FF76.0b4 + Windows 10. Maybe you've got more luck with a fresh profile.

**Comment by numpa** [comment]
It started working after downgrade to 3.3 and then upgrade to 3.4 (for some reason reinstallation didn't work). But while it wasn't working I was searching for some other solution. And I've found one. Check for yourself.
https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases
