### ISSUE TITLE
Make tab box scrollable + follow focused tab

### ISSUE THREAD

**Issue by numirias** [numirias/paxmod#62]
[...] you cannot scroll within the tab area using the scrollwheel. Ctrl-PgUp/Dn
and Alt-1..9 (or Ctrl-1..9) do work, and the scrollbar for the tab area is also showing,
but using the scrollwheel does not do anything.

_Originally posted by @mjk-gh in https://github.com/numirias/paxmod/issues/48#issuecomment-644140805_

**Comment by adisor19** [comment]
This seems to be the same issue as my bug report #74
