### ISSUE TITLE
Tab color settings ignored

### ISSUE THREAD

**Issue by einicher** [numirias/paxmod#68]
ubuntu 20.20, firefox 81 nightly

when i disable tab colors in pref, all colors are set back to white, but when i open new tabs, the are colored again. My whole operating system is dark theme, so those colors make tabs unreadable for me.

![image](https://user-images.githubusercontent.com/948188/90164374-9ce0cd80-dd97-11ea-812e-e04bac591625.png)

**Comment by jtagcat** [comment]
cc #66 v81 seems to have broken most features.

**Comment by numirias** [comment]
I'm closing this for now as a duplicate of #66 (which is fixed in the latest release). Feel free to reopen the issue if your problem isn't solved.
