### ISSUE TITLE
Multiple rows issue

### ISSUE THREAD

**Issue by nakleng44** [numirias/paxmod#70]
Is there a way to see all the rows and tabs like before instead of seeing just 2 rows and scroll?

**Environment**
win10, Firefox developer edition 81.0b9, Paxmod version 3.5

**Comment by jtagcat** [comment]
Duplicate of #66.

**Comment by nakleng44** [comment]
> Duplicate of #66.

not really

**Comment by numirias** [comment]
Duplicate of #66, should be fixed in latest release. Feel free to reopen if the problem persists.
