### ISSUE TITLE
Unable to scroll multiple rows of tabs

### ISSUE THREAD

**Issue by adisor19** [numirias/paxmod#74]
So i restarted Firefox 83.0b10 and reopened it just to see if my tab session will come back up and it did. However, i am no longer able to scroll my multiple rows of tabs using my trackpad. I see a scroll bar appearing at the right side of the browser when I attempt to scroll using my trackpad but nothing happens. If I go ahead and pull the scroll bar, it does scroll my tab rows.. this was working just fine literally 5 minutes ago before i restarted my browser..

<img width="202" alt="Screen Shot 2020-11-16 at 9 27 19 AM" src="https://user-images.githubusercontent.com/9268200/99264010-ef45e600-27ed-11eb-9222-c337ef50ab1e.png">

This is on macOS BigSur 11.0.1 running Firefox Dev 83.0b10..

**Comment by adisor19** [comment]
Just managed to reproduce this with FF Nightly as well. Upon first launch of Nightly and with a virgin profile, when I install Paxmod, i can scroll all my rows of tabs with no problem. As soon as I quit Nightly and restart it, I can no longer scroll my multile rows of tabs by using the trackpad gesture..

**Comment by adisor19** [comment]
I figured out what breaks it. It's the tab session restore of Firefox. If I uncheck the Restore previous session and Firefox starts up, i can add as many tabs as i want and the multiple rows of tabs will scroll just fine. As soon as I activate Restore previous session, Firefox does restore the last session and all its multiple rows of tabs, but i am unable to scroll the multiple rows of tabs. 

Any way to fix this ?

**Comment by numirias** [comment]
Thanks for investigating the issue. Unfortunately I'm not entirely sure what Firefox-internal logic causes the scroll events to fail in the case you described.

I will possibly look into this some time in the future, but since stuff related to scrolling and rearranging tabs can be a little more tricky and fragile, I don't have the resources right now. But I'll happily take patches.

**Comment by adisor19** [comment]
Hi, glad the project is still alive and hopefully you'll be able to look into this at one point. I'm a complete noob when it comes to coding so unfortunately, I can't submit any patches :/ That being said I'd happily throw some $ at the problem or as a thank you token. Got a donation box setup anywhere ?

**Comment by numirias** [comment]
Release v3.9 should fix this. (You'll need to restart the browser after the update.) Feel free to reopen if the problem still appears.

Also, thanks for offering your support. For now I don't plan to take donations - I want to avoid the extra work that probably comes with it, or any false expectations donors may get after donating. But I appreciate it.

The best way of support is telling others about the project. It's more fun to maintain something that has an actual user base. Also, detailed bug reports, and answering to other peoples' issues (many are just misconfigurations) helps a lot.

**Comment by adisor19** [comment]
Hi,

I can confirm this fixes the problem. Thank you very much for looking into it!

If ever you setup a donation box, let me know. This tool is essential for my daily workflow and I’d love to contribute somehow.

Thank you,

Adi
