### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by adisor19** [numirias/paxmod#76]
I reported a while ago that restored sessions with multiple rows of tabs that are ABOVE the maximum set allowed don't scroll either under Windows or macOS.

No replies whatsoever.. :/ At this point I'm looking to find out what is the last version of Firefox that actually worked correctly so if anyone knows, do let me know.

Thank you

**Comment by numirias** [comment]
I understand that you made an effort to write up the bug report and really want this fixed. However, I don't have any co-contributors and don't always find the time to process all bugs.

The project is alive in the sense that I use Paxmod daily and intend to keep it working.
