### ISSUE TITLE
Coloring not working on Firefox Developer 88.0b2 (64 bit)

### ISSUE THREAD

**Issue by olaims** [numirias/paxmod#77]
**Describe the bug**
After my last update of firefox Developer, the colouring of the tabs seems not to be working. All Tab titles are now white. 

**Environment**
Windows 10
Firefox Developer 88.0b2 (64 bit)
PaxMod 3.6

**Comment by numirias** [comment]
Thanks for reporting, the new release should fix this. :)
(You should be able to receive the new version via auto-update.)

**Comment by olaims** [comment]
thank you!!
