### ISSUE TITLE
tab colors too dark, impossible to read:

### ISSUE THREAD

**Issue by skrivskithar** [numirias/paxmod#78]
Since the last update, tab colors are TOO dark, rendering them impossible to read:
![Screenshot 2021-04-13 124601](https://user-images.githubusercontent.com/11478521/114581605-3974ab80-9c56-11eb-9386-078f2b8bf3bc.png)

**Comment by numirias** [comment]
Usually the tab color lightness range adjusts dynamically depending on whether you use a dark or light theme.

If it doesn't, you should be able to tweak that in the settings:

![settings](https://user-images.githubusercontent.com/29267777/114610052-c6902280-9c9f-11eb-957c-5ff0e157b9df.png)

**Comment by skrivskithar** [comment]
> 
> 
> Usually the tab color lightness range adjusts dynamically depending on whether you use a dark or light theme.
> 
> If it doesn't, you should be able to tweak that in the settings:
> 
> ![settings](https://user-images.githubusercontent.com/29267777/114610052-c6902280-9c9f-11eb-957c-5ff0e157b9df.png)

how did I miss this! unchecking the "fit lightness to themes" solved it for me, I'm using a dark theme. Thanks!
