### ISSUE TITLE
Playing audio text changes tab height

### ISSUE THREAD

**Issue by daugvinasr** [numirias/paxmod#86]
If you play anything with audio or video tab height changes. Is there a way to disable this behavior?
![image](https://user-images.githubusercontent.com/13218290/161829378-6a8f9140-0ad8-4ac4-bdff-35288f16058f.png)
![image](https://user-images.githubusercontent.com/13218290/161829392-45559fe4-6dac-4a9d-b6b4-1e2d0dd18054.png)

Windows 11 21H2, Firefox Nightly 101.0a1, Paxmod v3.12

**Comment by numirias** [comment]
There is a fallback behavior for layouts/languages where that "PLAYING" label would take too much space so icon indicators are used instead of text. The fix in numirias/paxmod@77a6b67 mimics that behavior and should fix the tab height.
