### ISSUE TITLE
[Windows 10] Tabs does not fill all the menu area into last Firefox Nightly

### ISSUE THREAD

**Issue by maioni** [numirias/paxmod#88]
**Describe the bug**
Tabs does not fill all the menu area into last Firefox Nightly

Firefox Nightly Version: 102.0a1 (2022-05-26) (64-bit)

I have 29 tabs pinned, and 72 other tabs not pinned:
![Issue](https://user-images.githubusercontent.com/6604846/170575970-bb9b42f5-bfff-4be7-8b6c-2027604010d9.png)

**Environment**
Reproducible on Windows 10 Pro
Not Reproducile on Linux Pop_OS! 22.04

**Settings**
My Settings:
![MySettings](https://user-images.githubusercontent.com/6604846/170578476-e3f558d1-0237-4023-b68e-569b0854ff0b.png)

Default was:
![Default](https://user-images.githubusercontent.com/6604846/170579026-c62e492a-d57c-49e2-b929-380c1066e77d.png)

**Comment by numirias** [comment]
Thanks, I'll look into it! (Also can't confirm it on Linux. Maybe related to the titlebar.)

**Comment by maioni** [comment]
It's only reproducible if the window has pinned tabs.

**Comment by maioni** [comment]
And also, when the windows is restored.

**Comment by UNKOWNFEAR** [comment]
I have the same problem. Please fix it as soon as possible :)

**Comment by sinyb** [comment]
Hello!

I can confirm the same problem in Nightly on Opensuse Tumbleweed 102.0a1 (2022-05-30) (64-bit).

So this is NOT Windows specific...

**Comment by numirias** [comment]
> So this is NOT Windows specific...

Thanks for pointing out, that made it easier! And thanks to the others for confirming.

I think [v3.13](https://github.com/numirias/paxmod/releases/tag/v3.13) (i.e. latest update) should fix this, please check.

**Comment by sinyb** [comment]
I can confirm that everything is fine again after update to 3.13.

Thank you very much and keep up the good work!
