### ISSUE TITLE
Button to switch to light theme

### ISSUE THREAD

**Issue by nightspectre12** [numirias/paxmod#9]
Hi,

Like we speak on reddit there will be great to switch between dark and light theme.
Now users can style this manually, but for most do this like on screen is very hard.

**Comment by numirias** [comment]
Thanks for reporting!

In the [most recent version](https://github.com/numirias/paxmod/releases) I added a switch to the options to easily toggle between the light and dark presets.

Note that I made heavy changes to the code and as a result the appearance of the light preset has changed a bit, too.

Also, in theory, you can now use one of the built-in themes (at `about:addons` > Themes) alongside paxmod after disabling *Custom theme colors* in the settings.

**Comment by nightspectre12** [comment]
It's look great!
Thx for good work!
