### ISSUE TITLE
Not all tabs are shown since Aug 12 or 13 update

### ISSUE THREAD

**Issue by sinyb** [numirias/paxmod#90]
Hello!
Since yesterdays update (maybe a day or two earlier, I did not update my Nightly for a few days), maximum of two rows are ever shown, and even then some tabs are missing.  Happens in Linux (openSUSE Tumbleweed) and Windows 11. 
In Developer edition 104.x everything is OK, all 54 tabs visible, but in Nightly I can see only 3-4 tabs comming after 25 pinned ones (I usually have 30 pinned, but tried to reduce the number for test - did not help). On Aug 11 everything was fine.
It seems that there is something wrong with the width of the tab bar, so Firefox "thinks" that there is much more space that there actualy is and places tabs beyond the window/screen width. When I open new tab (Ctrl-T), one tab appears in second row for every 3 new tabs I open.

**Comment by enki1337** [comment]
Same problem here as well on Windows 7. Looks like something in the nightly messed things up.

**Comment by gammy** [comment]
Replicated on 105.0a1 (2022-08-15) as well (Artix Linux (rolling)). Paxmod seems unaware of the width of the window; changing width of the browser has no effect on the positioning/size/rows of tabs.
