### ISSUE TITLE
Moving tabs from another window is not possible into second row

### ISSUE THREAD

**Issue by nazar-pc** [numirias/paxmod#93]
**Describe the bug**
1. Open two windows
2. Make first window contain enough tabs to occupy two or more rows
3. Try to move a tab from second window into the first one onto the second row

**Environment**
Ubuntu 22.04
Qtile window manager
Firefox Nightly (106.0a1 (2022-09-05) right now)
Paxmod 3.15

**Comment by Jolly-Pirate** [comment]
This has been a problem with other css mods as well. I found paxmod and gave it a try, it works nicely. I had to switch from FF 128 to the latest Nightly 130 to be able to use it.

**Comment by nazar-pc** [comment]
Yes, just tested and it does seem to work now
