### ISSUE TITLE
Stopped working in last 2 nightly builds

### ISSUE THREAD

**Issue by nazar-pc** [numirias/paxmod#96]
**Describe the bug**
It breaks top part of the browser completely, address bar isn't even visible, native browser pages like page with extensions doesn't render anymore either.

**Environment**
Firefox 107.0a1 (2022-10-15)
Paxmod 3.15
Linux

**Comment by sentix001** [comment]
same for me

**Comment by numirias** [comment]
Aaah, I wasn't able to fix it in time. Should be patched now. Thanks for the early report.
